baseURL = "https://jmonkeyengine.org/"
languageCode = "en-us"
title = "jMonkeyEngine"
theme = "ananke"

googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "A cross-platform game engine for adventurous Java developers."
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/jMonkeyEngine/jmonkeyengine"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  discourse = "https://hub.jmonkeyengine.org"
  discord = "https://discord.gg/JdjhsRw"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/header.webp"
  recent_posts_number = 2
  custom_css = ["css/style.css"]

[taxonomies]
  author = "authors"