baseURL = "https://jmonkeyengine.org/"
languageCode = "en-us"
title = "jMonkeyEngine"
paginate=9

googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"



[params]
  favicon = ""
  description = "A cross-platform game engine for adventurous Java developers."
  twitter = ""
  youtube = ""
  github = "https://github.com/jMonkeyEngine/jmonkeyengine"
  discord = "https://discord.gg/JdjhsRw"
  featured_image = "/images/header.webp"
  recent_posts_number = 2

  custom_css = ["css/style.css"]

[taxonomies]
  author = "authors"
  tag = "tags"
