name: Publish
on:
  push:

jobs:
  build:
    runs-on: ubuntu-18.04    
    steps:
    
    - name: Prepare
      run: |
        sudo apt-get update
        sudo apt-get install -y hugo
  
    - name: Clone repo
      run: |
        git config --global user.name "GithubActions"
        git config --global user.email "actions@robot.frk.wf"
        git clone https://github.com/${GITHUB_REPOSITORY}.git .
        git fetch origin gh-pages:gh-pages
        git checkout $GITHUB_SHA
        rm -Rvf public
         
    - name: Update data     
      run: |        
        hugo
        cp -Rf public ..
        git reset --hard HEAD
        git checkout gh-pages
        mv -f ../public/* .
        git add *
        git commit -m "Update data - `date`"
        header=$(echo -n "ad-m:${{ secrets.GITHUB_TOKEN }}" | base64)
        (git -c http.extraheader="AUTHORIZATION: basic $header" push origin gh-pages --force) || true
        exit 0
